package com.pharosmed.walker.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pharosmed.walker.beans.EvaluateEntity;
import com.pharosmed.walker.beans.GloveBean;
import com.pharosmed.walker.beans.PlanEntity;
import com.pharosmed.walker.beans.SubPlanEntity;
import com.pharosmed.walker.beans.TrainDataEntity;
import com.pharosmed.walker.beans.UserBean;
import com.pharosmed.walker.beans.UserTrainRecordEntity;

import com.pharosmed.walker.greendao.EvaluateEntityDao;
import com.pharosmed.walker.greendao.GloveBeanDao;
import com.pharosmed.walker.greendao.PlanEntityDao;
import com.pharosmed.walker.greendao.SubPlanEntityDao;
import com.pharosmed.walker.greendao.TrainDataEntityDao;
import com.pharosmed.walker.greendao.UserBeanDao;
import com.pharosmed.walker.greendao.UserTrainRecordEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig evaluateEntityDaoConfig;
    private final DaoConfig gloveBeanDaoConfig;
    private final DaoConfig planEntityDaoConfig;
    private final DaoConfig subPlanEntityDaoConfig;
    private final DaoConfig trainDataEntityDaoConfig;
    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig userTrainRecordEntityDaoConfig;

    private final EvaluateEntityDao evaluateEntityDao;
    private final GloveBeanDao gloveBeanDao;
    private final PlanEntityDao planEntityDao;
    private final SubPlanEntityDao subPlanEntityDao;
    private final TrainDataEntityDao trainDataEntityDao;
    private final UserBeanDao userBeanDao;
    private final UserTrainRecordEntityDao userTrainRecordEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        evaluateEntityDaoConfig = daoConfigMap.get(EvaluateEntityDao.class).clone();
        evaluateEntityDaoConfig.initIdentityScope(type);

        gloveBeanDaoConfig = daoConfigMap.get(GloveBeanDao.class).clone();
        gloveBeanDaoConfig.initIdentityScope(type);

        planEntityDaoConfig = daoConfigMap.get(PlanEntityDao.class).clone();
        planEntityDaoConfig.initIdentityScope(type);

        subPlanEntityDaoConfig = daoConfigMap.get(SubPlanEntityDao.class).clone();
        subPlanEntityDaoConfig.initIdentityScope(type);

        trainDataEntityDaoConfig = daoConfigMap.get(TrainDataEntityDao.class).clone();
        trainDataEntityDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        userTrainRecordEntityDaoConfig = daoConfigMap.get(UserTrainRecordEntityDao.class).clone();
        userTrainRecordEntityDaoConfig.initIdentityScope(type);

        evaluateEntityDao = new EvaluateEntityDao(evaluateEntityDaoConfig, this);
        gloveBeanDao = new GloveBeanDao(gloveBeanDaoConfig, this);
        planEntityDao = new PlanEntityDao(planEntityDaoConfig, this);
        subPlanEntityDao = new SubPlanEntityDao(subPlanEntityDaoConfig, this);
        trainDataEntityDao = new TrainDataEntityDao(trainDataEntityDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        userTrainRecordEntityDao = new UserTrainRecordEntityDao(userTrainRecordEntityDaoConfig, this);

        registerDao(EvaluateEntity.class, evaluateEntityDao);
        registerDao(GloveBean.class, gloveBeanDao);
        registerDao(PlanEntity.class, planEntityDao);
        registerDao(SubPlanEntity.class, subPlanEntityDao);
        registerDao(TrainDataEntity.class, trainDataEntityDao);
        registerDao(UserBean.class, userBeanDao);
        registerDao(UserTrainRecordEntity.class, userTrainRecordEntityDao);
    }
    
    public void clear() {
        evaluateEntityDaoConfig.clearIdentityScope();
        gloveBeanDaoConfig.clearIdentityScope();
        planEntityDaoConfig.clearIdentityScope();
        subPlanEntityDaoConfig.clearIdentityScope();
        trainDataEntityDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
        userTrainRecordEntityDaoConfig.clearIdentityScope();
    }

    public EvaluateEntityDao getEvaluateEntityDao() {
        return evaluateEntityDao;
    }

    public GloveBeanDao getGloveBeanDao() {
        return gloveBeanDao;
    }

    public PlanEntityDao getPlanEntityDao() {
        return planEntityDao;
    }

    public SubPlanEntityDao getSubPlanEntityDao() {
        return subPlanEntityDao;
    }

    public TrainDataEntityDao getTrainDataEntityDao() {
        return trainDataEntityDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public UserTrainRecordEntityDao getUserTrainRecordEntityDao() {
        return userTrainRecordEntityDao;
    }

}
