package com.pharosmed.walker.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.pharosmed.walker.beans.EvaluateEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EVALUATE_VALUE".
*/
public class EvaluateEntityDao extends AbstractDao<EvaluateEntity, Long> {

    public static final String TABLENAME = "EVALUATE_VALUE";

    /**
     * Properties of entity EvaluateEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property EvaluateResult = new Property(2, int.class, "evaluateResult", false, "EVALUATE_RESULT");
        public final static Property CreateDate = new Property(3, long.class, "createDate", false, "CREATE_DATE");
        public final static Property Vas = new Property(4, int.class, "vas", false, "VAS");
    }


    public EvaluateEntityDao(DaoConfig config) {
        super(config);
    }
    
    public EvaluateEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EVALUATE_VALUE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"EVALUATE_RESULT\" INTEGER NOT NULL ," + // 2: evaluateResult
                "\"CREATE_DATE\" INTEGER NOT NULL ," + // 3: createDate
                "\"VAS\" INTEGER NOT NULL );"); // 4: vas
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EVALUATE_VALUE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EvaluateEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getEvaluateResult());
        stmt.bindLong(4, entity.getCreateDate());
        stmt.bindLong(5, entity.getVas());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EvaluateEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getEvaluateResult());
        stmt.bindLong(4, entity.getCreateDate());
        stmt.bindLong(5, entity.getVas());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public EvaluateEntity readEntity(Cursor cursor, int offset) {
        EvaluateEntity entity = new EvaluateEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.getInt(offset + 2), // evaluateResult
            cursor.getLong(offset + 3), // createDate
            cursor.getInt(offset + 4) // vas
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EvaluateEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setEvaluateResult(cursor.getInt(offset + 2));
        entity.setCreateDate(cursor.getLong(offset + 3));
        entity.setVas(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(EvaluateEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(EvaluateEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(EvaluateEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
