package com.pharosmed.walker.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.pharosmed.walker.beans.SubPlanEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SUB_TRAIN_PLAN".
*/
public class SubPlanEntityDao extends AbstractDao<SubPlanEntity, Long> {

    public static final String TABLENAME = "SUB_TRAIN_PLAN";

    /**
     * Properties of entity SubPlanEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property PlanId = new Property(2, long.class, "planId", false, "PLAN_ID");
        public final static Property PlanStatus = new Property(3, int.class, "planStatus", false, "PLAN_STATUS");
        public final static Property ClassId = new Property(4, int.class, "classId", false, "CLASS_ID");
        public final static Property Load = new Property(5, int.class, "load", false, "LOAD");
        public final static Property WeekNum = new Property(6, int.class, "weekNum", false, "WEEK_NUM");
        public final static Property DayNum = new Property(7, int.class, "dayNum", false, "DAY_NUM");
        public final static Property StartDate = new Property(8, String.class, "startDate", false, "START_DATE");
        public final static Property EndDate = new Property(9, String.class, "endDate", false, "END_DATE");
    }


    public SubPlanEntityDao(DaoConfig config) {
        super(config);
    }
    
    public SubPlanEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SUB_TRAIN_PLAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"PLAN_ID\" INTEGER NOT NULL ," + // 2: planId
                "\"PLAN_STATUS\" INTEGER NOT NULL ," + // 3: planStatus
                "\"CLASS_ID\" INTEGER NOT NULL ," + // 4: classId
                "\"LOAD\" INTEGER NOT NULL ," + // 5: load
                "\"WEEK_NUM\" INTEGER NOT NULL ," + // 6: weekNum
                "\"DAY_NUM\" INTEGER NOT NULL ," + // 7: dayNum
                "\"START_DATE\" TEXT," + // 8: startDate
                "\"END_DATE\" TEXT);"); // 9: endDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SUB_TRAIN_PLAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SubPlanEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getPlanId());
        stmt.bindLong(4, entity.getPlanStatus());
        stmt.bindLong(5, entity.getClassId());
        stmt.bindLong(6, entity.getLoad());
        stmt.bindLong(7, entity.getWeekNum());
        stmt.bindLong(8, entity.getDayNum());
 
        String startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindString(9, startDate);
        }
 
        String endDate = entity.getEndDate();
        if (endDate != null) {
            stmt.bindString(10, endDate);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SubPlanEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getPlanId());
        stmt.bindLong(4, entity.getPlanStatus());
        stmt.bindLong(5, entity.getClassId());
        stmt.bindLong(6, entity.getLoad());
        stmt.bindLong(7, entity.getWeekNum());
        stmt.bindLong(8, entity.getDayNum());
 
        String startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindString(9, startDate);
        }
 
        String endDate = entity.getEndDate();
        if (endDate != null) {
            stmt.bindString(10, endDate);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SubPlanEntity readEntity(Cursor cursor, int offset) {
        SubPlanEntity entity = new SubPlanEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.getLong(offset + 2), // planId
            cursor.getInt(offset + 3), // planStatus
            cursor.getInt(offset + 4), // classId
            cursor.getInt(offset + 5), // load
            cursor.getInt(offset + 6), // weekNum
            cursor.getInt(offset + 7), // dayNum
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // startDate
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // endDate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SubPlanEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setPlanId(cursor.getLong(offset + 2));
        entity.setPlanStatus(cursor.getInt(offset + 3));
        entity.setClassId(cursor.getInt(offset + 4));
        entity.setLoad(cursor.getInt(offset + 5));
        entity.setWeekNum(cursor.getInt(offset + 6));
        entity.setDayNum(cursor.getInt(offset + 7));
        entity.setStartDate(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setEndDate(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SubPlanEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SubPlanEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SubPlanEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
