package com.pharosmed.walker.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.pharosmed.walker.beans.TrainDataEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRAIN_DATA".
*/
public class TrainDataEntityDao extends AbstractDao<TrainDataEntity, Long> {

    public static final String TABLENAME = "TRAIN_DATA";

    /**
     * Properties of entity TrainDataEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property CreateDate = new Property(2, long.class, "createDate", false, "CREATE_DATE");
        public final static Property Frequency = new Property(3, int.class, "frequency", false, "FREQUENCY");
        public final static Property TargetLoad = new Property(4, int.class, "targetLoad", false, "TARGET_LOAD");
        public final static Property RealLoad = new Property(5, int.class, "realLoad", false, "REAL_LOAD");
        public final static Property PlanId = new Property(6, long.class, "planId", false, "PLAN_ID");
        public final static Property ClassId = new Property(7, int.class, "classId", false, "CLASS_ID");
        public final static Property IsUpload = new Property(8, int.class, "isUpload", false, "IS_UPLOAD");
        public final static Property DateStr = new Property(9, String.class, "dateStr", false, "DATE_STR");
    }


    public TrainDataEntityDao(DaoConfig config) {
        super(config);
    }
    
    public TrainDataEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRAIN_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"CREATE_DATE\" INTEGER NOT NULL ," + // 2: createDate
                "\"FREQUENCY\" INTEGER NOT NULL ," + // 3: frequency
                "\"TARGET_LOAD\" INTEGER NOT NULL ," + // 4: targetLoad
                "\"REAL_LOAD\" INTEGER NOT NULL ," + // 5: realLoad
                "\"PLAN_ID\" INTEGER NOT NULL ," + // 6: planId
                "\"CLASS_ID\" INTEGER NOT NULL ," + // 7: classId
                "\"IS_UPLOAD\" INTEGER NOT NULL ," + // 8: isUpload
                "\"DATE_STR\" TEXT);"); // 9: dateStr
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRAIN_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TrainDataEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getCreateDate());
        stmt.bindLong(4, entity.getFrequency());
        stmt.bindLong(5, entity.getTargetLoad());
        stmt.bindLong(6, entity.getRealLoad());
        stmt.bindLong(7, entity.getPlanId());
        stmt.bindLong(8, entity.getClassId());
        stmt.bindLong(9, entity.getIsUpload());
 
        String dateStr = entity.getDateStr();
        if (dateStr != null) {
            stmt.bindString(10, dateStr);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TrainDataEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getCreateDate());
        stmt.bindLong(4, entity.getFrequency());
        stmt.bindLong(5, entity.getTargetLoad());
        stmt.bindLong(6, entity.getRealLoad());
        stmt.bindLong(7, entity.getPlanId());
        stmt.bindLong(8, entity.getClassId());
        stmt.bindLong(9, entity.getIsUpload());
 
        String dateStr = entity.getDateStr();
        if (dateStr != null) {
            stmt.bindString(10, dateStr);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TrainDataEntity readEntity(Cursor cursor, int offset) {
        TrainDataEntity entity = new TrainDataEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.getLong(offset + 2), // createDate
            cursor.getInt(offset + 3), // frequency
            cursor.getInt(offset + 4), // targetLoad
            cursor.getInt(offset + 5), // realLoad
            cursor.getLong(offset + 6), // planId
            cursor.getInt(offset + 7), // classId
            cursor.getInt(offset + 8), // isUpload
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // dateStr
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TrainDataEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setCreateDate(cursor.getLong(offset + 2));
        entity.setFrequency(cursor.getInt(offset + 3));
        entity.setTargetLoad(cursor.getInt(offset + 4));
        entity.setRealLoad(cursor.getInt(offset + 5));
        entity.setPlanId(cursor.getLong(offset + 6));
        entity.setClassId(cursor.getInt(offset + 7));
        entity.setIsUpload(cursor.getInt(offset + 8));
        entity.setDateStr(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TrainDataEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TrainDataEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TrainDataEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
