package com.pharosmed.walker.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.pharosmed.walker.beans.UserTrainRecordEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_TRAIN_RECORD".
*/
public class UserTrainRecordEntityDao extends AbstractDao<UserTrainRecordEntity, Long> {

    public static final String TABLENAME = "USER_TRAIN_RECORD";

    /**
     * Properties of entity UserTrainRecordEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property SuccessTime = new Property(2, int.class, "successTime", false, "SUCCESS_TIME");
        public final static Property WarningTime = new Property(3, int.class, "warningTime", false, "WARNING_TIME");
        public final static Property TrainTime = new Property(4, int.class, "trainTime", false, "TRAIN_TIME");
        public final static Property Score = new Property(5, int.class, "score", false, "SCORE");
        public final static Property PainLevel = new Property(6, int.class, "painLevel", false, "PAIN_LEVEL");
        public final static Property AdverseReactions = new Property(7, String.class, "adverseReactions", false, "ADVERSE_REACTIONS");
        public final static Property TargetLoad = new Property(8, int.class, "targetLoad", false, "TARGET_LOAD");
        public final static Property CreateDate = new Property(9, long.class, "createDate", false, "CREATE_DATE");
        public final static Property Frequency = new Property(10, int.class, "frequency", false, "FREQUENCY");
        public final static Property Diagnostic = new Property(11, String.class, "diagnostic", false, "DIAGNOSTIC");
        public final static Property Str = new Property(12, String.class, "str", false, "STR");
        public final static Property PlanId = new Property(13, long.class, "planId", false, "PLAN_ID");
        public final static Property ClassId = new Property(14, int.class, "classId", false, "CLASS_ID");
        public final static Property DateStr = new Property(15, String.class, "dateStr", false, "DATE_STR");
    }


    public UserTrainRecordEntityDao(DaoConfig config) {
        super(config);
    }
    
    public UserTrainRecordEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_TRAIN_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"SUCCESS_TIME\" INTEGER NOT NULL ," + // 2: successTime
                "\"WARNING_TIME\" INTEGER NOT NULL ," + // 3: warningTime
                "\"TRAIN_TIME\" INTEGER NOT NULL ," + // 4: trainTime
                "\"SCORE\" INTEGER NOT NULL ," + // 5: score
                "\"PAIN_LEVEL\" INTEGER NOT NULL ," + // 6: painLevel
                "\"ADVERSE_REACTIONS\" TEXT," + // 7: adverseReactions
                "\"TARGET_LOAD\" INTEGER NOT NULL ," + // 8: targetLoad
                "\"CREATE_DATE\" INTEGER NOT NULL ," + // 9: createDate
                "\"FREQUENCY\" INTEGER NOT NULL ," + // 10: frequency
                "\"DIAGNOSTIC\" TEXT," + // 11: diagnostic
                "\"STR\" TEXT," + // 12: str
                "\"PLAN_ID\" INTEGER NOT NULL ," + // 13: planId
                "\"CLASS_ID\" INTEGER NOT NULL ," + // 14: classId
                "\"DATE_STR\" TEXT);"); // 15: dateStr
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_TRAIN_RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserTrainRecordEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getSuccessTime());
        stmt.bindLong(4, entity.getWarningTime());
        stmt.bindLong(5, entity.getTrainTime());
        stmt.bindLong(6, entity.getScore());
        stmt.bindLong(7, entity.getPainLevel());
 
        String adverseReactions = entity.getAdverseReactions();
        if (adverseReactions != null) {
            stmt.bindString(8, adverseReactions);
        }
        stmt.bindLong(9, entity.getTargetLoad());
        stmt.bindLong(10, entity.getCreateDate());
        stmt.bindLong(11, entity.getFrequency());
 
        String diagnostic = entity.getDiagnostic();
        if (diagnostic != null) {
            stmt.bindString(12, diagnostic);
        }
 
        String str = entity.getStr();
        if (str != null) {
            stmt.bindString(13, str);
        }
        stmt.bindLong(14, entity.getPlanId());
        stmt.bindLong(15, entity.getClassId());
 
        String dateStr = entity.getDateStr();
        if (dateStr != null) {
            stmt.bindString(16, dateStr);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserTrainRecordEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getSuccessTime());
        stmt.bindLong(4, entity.getWarningTime());
        stmt.bindLong(5, entity.getTrainTime());
        stmt.bindLong(6, entity.getScore());
        stmt.bindLong(7, entity.getPainLevel());
 
        String adverseReactions = entity.getAdverseReactions();
        if (adverseReactions != null) {
            stmt.bindString(8, adverseReactions);
        }
        stmt.bindLong(9, entity.getTargetLoad());
        stmt.bindLong(10, entity.getCreateDate());
        stmt.bindLong(11, entity.getFrequency());
 
        String diagnostic = entity.getDiagnostic();
        if (diagnostic != null) {
            stmt.bindString(12, diagnostic);
        }
 
        String str = entity.getStr();
        if (str != null) {
            stmt.bindString(13, str);
        }
        stmt.bindLong(14, entity.getPlanId());
        stmt.bindLong(15, entity.getClassId());
 
        String dateStr = entity.getDateStr();
        if (dateStr != null) {
            stmt.bindString(16, dateStr);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserTrainRecordEntity readEntity(Cursor cursor, int offset) {
        UserTrainRecordEntity entity = new UserTrainRecordEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.getInt(offset + 2), // successTime
            cursor.getInt(offset + 3), // warningTime
            cursor.getInt(offset + 4), // trainTime
            cursor.getInt(offset + 5), // score
            cursor.getInt(offset + 6), // painLevel
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // adverseReactions
            cursor.getInt(offset + 8), // targetLoad
            cursor.getLong(offset + 9), // createDate
            cursor.getInt(offset + 10), // frequency
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // diagnostic
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // str
            cursor.getLong(offset + 13), // planId
            cursor.getInt(offset + 14), // classId
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15) // dateStr
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserTrainRecordEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setSuccessTime(cursor.getInt(offset + 2));
        entity.setWarningTime(cursor.getInt(offset + 3));
        entity.setTrainTime(cursor.getInt(offset + 4));
        entity.setScore(cursor.getInt(offset + 5));
        entity.setPainLevel(cursor.getInt(offset + 6));
        entity.setAdverseReactions(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setTargetLoad(cursor.getInt(offset + 8));
        entity.setCreateDate(cursor.getLong(offset + 9));
        entity.setFrequency(cursor.getInt(offset + 10));
        entity.setDiagnostic(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setStr(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setPlanId(cursor.getLong(offset + 13));
        entity.setClassId(cursor.getInt(offset + 14));
        entity.setDateStr(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserTrainRecordEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserTrainRecordEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserTrainRecordEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
